[project]
name = "rnvt-repo"
version = "0.1.0"
description = ""
authors = [
    {name = "Mieszko Chowaniec",email = "mchowaniec@sphera.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow (>=12.3.0,<13.0.0)",
    "uvloop (>=0.22.1,<0.23.0)",
    "sqlalchemy (==1.3.18)",
    "aiohttp (==3.14.3)",
    "sympy (==1.13.1)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
